from .interspatial_correspondence_suggester import InterspatialCorrespondenceSuggester
from .space_to_frame_correspondence_suggester import SpaceToFrameCorrespondenceSuggester
from .sub_frame_to_frame_correspondence_suggester import (
    SubFrameToFrameCorrespondenceSuggester,
)
from .potential_sub_frame_to_frame_correspondence_suggester import (
    PotentialSubFrameToFrameCorrespondenceSuggester,
)
