# Generated by Django 3.1.1 on 2020-09-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20200922_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeletrecord',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.runrecord'),
        ),
        migrations.AlterField(
            model_name='perceptletrecord',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.runrecord'),
        ),
    ]
