# Generated by Django 3.1.1 on 2020-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_auto_20200922_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptletrecord',
            name='location',
            field=models.JSONField(null=True, verbose_name='location'),
        ),
    ]
