# Generated by Django 3.1.1 on 2020-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_auto_20200922_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderackrecord',
            name='codelets_run',
            field=models.JSONField(verbose_name='Codelets Run'),
        ),
        migrations.AlterField(
            model_name='coderackrecord',
            name='population',
            field=models.JSONField(verbose_name='Population'),
        ),
    ]
