# Generated by Django 3.1.1 on 2020-09-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_auto_20200923_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderackrecord',
            name='codelets_run',
            field=models.JSONField(verbose_name='Codelets Run'),
        ),
        migrations.AlterField(
            model_name='coderackrecord',
            name='population',
            field=models.JSONField(verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='perceptletrecord',
            name='quality',
            field=models.JSONField(verbose_name='quality'),
        ),
        migrations.CreateModel(
            name='PerceptletUpdateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('codelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.codeletrecord', unique=True)),
                ('perceptlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.perceptletrecord', unique=True)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.runrecord', unique=True)),
            ],
        ),
    ]
