# Generated by Django 3.1.1 on 2020-09-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_auto_20200925_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptletupdaterecord',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.runrecord'),
        ),
    ]
