# Generated by Django 3.1.1 on 2020-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0012_auto_20200925_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perceptletrecord',
            name='connections',
        ),
        migrations.AddField(
            model_name='perceptletrecord',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, related_name='_perceptletrecord_connections_+', to='runs.PerceptletRecord'),
        ),
    ]
