# Generated by Django 3.1.1 on 2020-09-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0013_auto_20200925_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptletupdaterecord',
            name='codelet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.codeletrecord'),
        ),
    ]
