# Generated by Django 3.1.1 on 2020-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0014_auto_20200925_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='perceptletrecord',
            name='first_argument',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Argument'),
        ),
        migrations.AddField(
            model_name='perceptletrecord',
            name='second_argument',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Argument'),
        ),
    ]
