from space_to_frame_correspondence_suggester import SpaceToFrameCorrespondenceSuggester
from sub_frame_to_frame_correspondence_suggester import (
    SubSpaceToFrameCorrespondenceSuggester,
)
from potential_sub_frame_to_frame_correspondence_suggester import (
    PotentialSubSpaceToFrameCorrespondenceSuggester,
)
