# Generated by Django 3.1.1 on 2020-09-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.JSONField(verbose_name='Series')),
            ],
        ),
        migrations.CreateModel(
            name='Codelet',
            fields=[
                ('codelet_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Codelet ID')),
                ('codelet_type', models.CharField(max_length=200, verbose_name='Codelet ID')),
                ('time_run', models.IntegerField(verbose_name='Time Run')),
                ('urgency', models.FloatField(verbose_name='Urgency')),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follow Up Codelet+', to='runs.codelet', unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='runs.codelet', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Concept ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.activationpattern')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time', models.DateTimeField(verbose_name='Completion Time')),
            ],
        ),
        migrations.CreateModel(
            name='Perceptlet',
            fields=[
                ('perceptlet_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Perceptlet ID')),
                ('time_created', models.IntegerField(verbose_name='Time Created')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('quality', models.JSONField(verbose_name='quality')),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.activationpattern')),
                ('connections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.perceptlet')),
                ('parent_codelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.codelet')),
                ('parent_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.concept')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run', unique=True)),
                ('unhappiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='runs.activationpattern')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run', unique=True),
        ),
        migrations.AddField(
            model_name='codelet',
            name='perceptlet_types',
            field=models.ManyToManyField(to='runs.Concept'),
        ),
        migrations.AddField(
            model_name='codelet',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run', unique=True),
        ),
        migrations.AddField(
            model_name='codelet',
            name='target_perceptlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.perceptlet'),
        ),
        migrations.AddField(
            model_name='activationpattern',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run', unique=True),
        ),
    ]
