class HyperParameters:
    FLOATING_POINT_TOLERANCE = 1e-5

    DECAY_RATE = 0.1
    CONFIDENCE_THRESHOLD = 0.5

    IMPORTANCE_WEIGHT = 0.4
    UNHAPPINESS_WEIGHT = 0.6

    GROUP_IMPORTANCE_SIZE_WEIGHT = 0.4
    GROUP_IMPORTANCE_LABEL_WEIGHT = 0.3
    GROUP_IMPORTANCE_STRENGTH_WEIGHT = 0.3

    SENTENCE_IMPORTANCE_SIZE_WEIGHT = 0.4
    SENTENCE_IMPORTANCE_LABEL_WEIGHT = 0.3
    SENTENCE_IMPORTANCE_STRENGTH_WEIGHT = 0.3
