class HyperParameters:
    ACTIVATION_UPDATE_FREQUENCY = 10
    FLOATING_POINT_TOLERANCE = 1e-5

    IDEAL_CODERACK_POPULATION = 10
    MINIMUM_CODELET_URGENCY = FLOATING_POINT_TOLERANCE

    EMOTION_CONCEPTUAL_DEPTH = 10

    DECAY_RATE = 0.1
    CONFIDENCE_THRESHOLD = 0.5

    PERCEPTLET_ACTIVATION_COEFFICIENT = 1

    # why are these uneven?
    EXIGENCY_ACTIVATION_WEIGHT = 0.4
    EXIGENCY_UNHAPPINESS_WEIGHT = 0.6

    # larger groups tend to have lower strength
    # so size has greatest weight to compensate
    GROUP_IMPORTANCE_SIZE_WEIGHT = 0.5
    GROUP_IMPORTANCE_LABEL_WEIGHT = 0.2
    GROUP_IMPORTANCE_TEXTLET_WEIGHT = 0.2
    GROUP_IMPORTANCE_STRENGTH_WEIGHT = 0.1

    CORRESPONDENCE_IMPORTANCE_LABEL_WEIGHT = 0.5
    CORRESPONDENCE_IMPORTANCE_STRENGTH_WEIGHT = 0.5

    TEXTLET_IMPORTANCE_SIZE_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_CONSTITUENT_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_LABEL_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_STRENGTH_WEIGHT = 0.25

    MAXIMUM_CONCEPT_DEPTH = 10
    MAXIMUM_DISTANCE_FROM_PROTOTYPE = 10
    DISTANCE_TO_PROXIMITY_WEIGHT = 1.5

    ACTIVATION_PATTERN_DEPTH = 1
    ACTIVATION_PATTERN_HEIGHT = 3
    ACTIVATION_PATTERN_WIDTH = 3
    WORKSPACE_DEPTH = 1
    WORKSPACE_HEIGHT = 6
    WORKSPACE_WIDTH = 5

    NO_OF_STARTER_CODELETS = 10
    STARTER_CODELET_URGENCY = 0.5
