class HyperParameters:
    ACTIVATION_UPDATE_FREQUENCY = 10

    FLOATING_POINT_TOLERANCE = 1e-5

    DECAY_RATE = 0.1
    CONFIDENCE_THRESHOLD = 0.5

    IMPORTANCE_WEIGHT = 0.4
    UNHAPPINESS_WEIGHT = 0.6

    GROUP_IMPORTANCE_SIZE_WEIGHT = 0.4
    GROUP_IMPORTANCE_LABEL_WEIGHT = 0.3
    GROUP_IMPORTANCE_STRENGTH_WEIGHT = 0.3

    CORRESPONDENCE_IMPORTANCE_LABEL_WEIGHT = 0.5
    CORRESPONDENCE_IMPORTANCE_STRENGTH_WEIGHT = 0.5

    TEXTLET_IMPORTANCE_SIZE_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_CONSTITUENT_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_LABEL_WEIGHT = 0.25
    TEXTLET_IMPORTANCE_STRENGTH_WEIGHT = 0.25

    MAXIMUM_CONCEPT_DEPTH = 10
    MAXIMUM_DISTANCE_FROM_PROTOTYPE = 10
    DISTANCE_TO_PROXIMITY_WEIGHT = 1.5

    ACTIVATION_PATTERN_DEPTH = 1
    ACTIVATION_PATTERN_HEIGHT = 3
    ACTIVATION_PATTERN_WIDTH = 3
    WORKSPACE_DEPTH = 1
    WORKSPACE_HEIGHT = 6
    WORKSPACE_WIDTH = 5

    NO_OF_STARTER_CODELETS = 5
    STARTER_CODELET_URGENCY = 0.5
