class HyperParameters:
    FLOATING_POINT_TOLERANCE = 1e-5
    CODELET_RUN_LIMIT = 20000

    ACTIVATION_UPDATE_FREQUENCY = 10
    ACTIVATION_UPDATE_COEFFICIENT = 0.5
    MINIMUM_ACTIVATION_UPDATE = 0.2
    DECAY_RATE = 0.1
    JUMP_THRESHOLD = 0.55

    MAXIMUM_CODERACK_POPULATION = 100
    MINIMUM_CODELET_URGENCY = 0.01
    NUMBER_OF_START_CHUNK_SUGGESTERS = 7

    DETERMINISM_SMOOTHING_FUNCTION = lambda x: (x + 0.8) / 2
    PUBLICATION_PROBABILITY_EXPONENT = 5

    # TODO: these ought to be specific to each conceptual space
    DISTANCE_TO_PROXIMITY_WEIGHT = 1
    HOW_FAR_IS_NEAR = 1

    ACTIVATION_LOGGING_FREQUENCY = 100

    TESTING = False
