class HyperParameters:
    FLOATING_POINT_TOLERANCE = 1e-5
    CODELET_RUN_LIMIT = 30000

    ACTIVATION_UPDATE_FREQUENCY = 10
    ACTIVATION_UPDATE_COEFFICIENT = 0.5
    MINIMUM_ACTIVATION_UPDATE = 0.2
    DECAY_RATE = 0.1
    JUMP_THRESHOLD = 0.55

    MAXIMUM_CODERACK_POPULATION = 100
    MINIMUM_CODELET_URGENCY = 0.01
    NUMBER_OF_START_CHUNK_SUGGESTERS = 7

    DETERMINISM_SMOOTHING_FUNCTION = lambda x: 0.5 * x + 0.25
    PUBLICATION_PROBABILITY_EXPONENT = 5

    # TODO: these ought to be specific to each conceptual space
    DISTANCE_TO_PROXIMITY_WEIGHT = 1
    HOW_FAR_IS_NEAR = 1

    ACTIVATION_LOGGING_FREQUENCY = 500

    TESTING = False

    VIEW_QUALITY_CORRESPONDENCE_WEIGHT = 0.25
    VIEW_QUALITY_INPUT_WEIGHT = 0.75

    RELATION_QUALITY_CLASSIFICATION_WEIGHT = 0.75
    RELATION_QUALITY_SAMENESS_WEIGHT = 0.25

    WORLDVIEW_QUALITY_PROPORTION_OF_INPUT_WEIGHT = 0.33
    WORLDVIEW_QUALITY_VIEW_QUALITY_WEIGHT = 0.33
    WORLDVIEW_QUALITY_NUMBER_OF_FRAMES_WEIGHT = 0.33

    BUBBLE_CHAMBER_SATISFACTION_MAIN_INPUT_WEIGHT = 0.25
    BUBBLE_CHAMBER_SATISFACTION_VIEW_QUALITIES_WEIGHT = 0.25
    BUBBLE_CHAMBER_SATISFACTION_WORLDVIEW_WEIGHT = 0.5
