(load "conceptual-spaces/grammar.lisp")
(load "conceptual-spaces/negativeness.lisp")
(load "conceptual-spaces/more-less.lisp")
(load "conceptual-spaces/same-different.lisp")
(load "conceptual-spaces/magnitude.lisp")
(load "conceptual-spaces/height.lisp")
(load "conceptual-spaces/goodness.lisp")
(load "conceptual-spaces/size.lisp")
(load "conceptual-spaces/lateness.lisp")
(load "conceptual-spaces/extremeness.lisp")
(load "conceptual-spaces/temperature.lisp")
(load "conceptual-spaces/peripheralness.lisp")
(load "conceptual-spaces/location.lisp")
(load "conceptual-spaces/time.lisp")

(load "frames/ap-jj.lisp")

(load "frames/pp-between-times.lisp")

(load "frames/pp-inessive-location.lisp")
(load "frames/pp-from-to-different-locations.lisp")
(load "frames/pp-from-wards-locations.lisp")

(load "frames/s-be.lisp")
(load "frames/s-increase.lisp")
(load "frames/s-move.lisp")
(load "frames/s-spread.lisp")
(load "frames/s-expand.lisp")

(load "frames/conj-null.lisp")
(load "frames/conj-temp.lisp")
